import Head from 'next/head'
import Intro from '../components/Intro'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials'
import {data} from '../data'

export default function Home({services}) {

  return (
    <div>
      <Head>
        <title>Web Agency</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
    <Intro/>
    <Services services={services}/>
    <Testimonials/>
      </main>

    </div>
  )
}

export const getStaticProps = () => {
  const services = data;
  return {
    props: { services },
  };
};